# Generated by Django 5.0.4 on 2024-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="replay",
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="replay",
            name="video",
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="game",
            name="short_name",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="replay",
            name="submitted_date",
            field=models.DateField(auto_now=True),
        ),
    ]
