# Generated by Django 5.0.4 on 2024-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0002_replay_replay_replay_video_alter_game_short_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="replay",
            field=models.FileField(upload_to=""),
        ),
    ]
