# Generated by Django 5.0.4 on 2024-04-24 17:38

import replays.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0003_alter_replay_replay"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(default="XXYY", max_length=16),
        ),
        migrations.AddField(
            model_name="game",
            name="code",
            field=models.CharField(default="thXX_ud", max_length=16),
        ),
        migrations.AlterField(
            model_name="replay",
            name="replay",
            field=models.FileField(upload_to=replays.models.replay_dir),
        ),
    ]
