# Generated by Django 5.0.4 on 2024-04-24 17:41

import replays.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0004_category_code_game_code_alter_replay_replay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="game",
            name="code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="replay",
            name="replay",
            field=models.FileField(blank=True, upload_to=replays.models.replay_dir),
        ),
    ]
