# Generated by Django 5.0.4 on 2024-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0005_alter_category_code_alter_game_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="route",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
