# Generated by Django 5.0.4 on 2024-05-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0007_alter_category_shot_alter_replay_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="shot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="replays.shottype",
            ),
        ),
        migrations.AlterField(
            model_name="shottype",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shots",
                to="replays.game",
            ),
        ),
    ]
