# Generated by Django 5.0.4 on 2024-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0008_alter_category_shot_alter_shottype_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="score",
            field=models.BigIntegerField(default=0),
        ),
    ]
