# Generated by Django 5.0.4 on 2024-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0009_replay_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
