# Generated by Django 5.0.4 on 2024-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0010_alter_replay_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
