# Generated by Django 5.0.4 on 2024-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0011_game_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="replay",
            name="verified",
            field=models.BooleanField(default=True),
        ),
    ]
