# Generated by Django 5.0.4 on 2024-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0012_replay_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="region",
            field=models.CharField(
                choices=[("Western", "Western"), ("Eastern", "Eastern")],
                default="Eastern",
                max_length=16,
            ),
        ),
    ]
