# Generated by Django 5.0.4 on 2024-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0013_category_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="replay",
            name="date",
            field=models.DateField(blank=True),
        ),
    ]
