# Generated by Django 5.0.4 on 2024-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0014_alter_category_options_alter_replay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
