# Generated by Django 5.0.4 on 2024-05-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0015_alter_replay_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shottype",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="replay",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
