# Generated by Django 5.0.4 on 2024-05-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0016_shottype_order_alter_game_number_alter_replay_date"),
        ("replays", "0017_alter_game_number"),
    ]

    operations = []
