# Generated by Django 5.0.4 on 2024-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0018_alter_shottype_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("url", models.URLField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("trigger_on_save", models.BooleanField(default=True)),
                ("trigger_on_delete", models.BooleanField(default=True)),
            ],
        ),
    ]
