# Generated by Django 5.0.4 on 2026-07-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0020_replay_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='score',
            field=models.BigIntegerField(default=0, help_text='If a replay file is included, the score will be set automatically.'),
        ),
    ]
