# Generated by Django 5.0.4 on 2026-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0021_alter_replay_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='replay',
            index=models.Index(fields=['category_id', '-score', 'submitted_date'], name='replay_highscore_idx'),
        ),
    ]
