# Generated by Django 5.0.4 on 2026-07-19 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0023_lnn_wr_maintainer_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replay",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="If a replay file is included, the category will be set automatically. For LNNs, set this field manually.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replays",
                to="replays.category",
            ),
        ),
        migrations.AlterField(
            model_name="replay",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="If a replay file is included, the date will be set automatically.",
                null=True,
            ),
        ),
    ]
