# Generated by Django 5.0.4 on 2026-08-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0024_alter_replay_category_alter_replay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If a replay file is included, the category will be set automatically.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='replays.category'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='replay',
            field=models.FileField(blank=True, upload_to='replays/tmp/'),
        ),
    ]
