"""
Django settings for touhou_replay_database project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_KEY",
    default="django-insecure-9z9em@lg087(4o0t0ei7&!8%+tz)*u#ld)+4t6x=tg@w=@hjaq",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", default=True) != "False"

ALLOWED_HOSTS = ["localhost", "maribelhearn.com"]

CSRF_TRUSTED_ORIGINS = [
    "https://maribelhearn.com",
    "http://localhost:6969",
    "http://127.0.0.1:6969",
]

# Application definition

INSTALLED_APPS = [
    "django_admin_kubi",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "replays",
    "rest_framework",
    "drf_spectacular",
    "rest_framework.authtoken",
    "django_filters",
    "corsheaders",
    "silk",
    "django_q",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "touhou_replay_database.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "touhou_replay_database.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST", default="127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", default="3306"),
    }
}


DJANGO_ADMIN_KUBI = {
    "ADMIN_HISTORY": True,  # enables the history action panel
    "ADMIN_SEARCH": True,  # enables a full modal search
}

# ADMIN_MENU = "replays.admin_menu.MyAdminMenu"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.AdminRenderer",
    ],
    # "DEFAULT_OBJECT_CACHE_KEY_FUNC": "replays.cache.ObjectKeyConstructor",
    # "DEFAULT_LIST_CACHE_KEY_FUNC": "replays.cache.ListKeyConstructor",
}

SILKY_AUTHENTICATION = True  # User must login
SILKY_AUTHORISATION = True  # User must have permissions
SILKY_PERMISSIONS = lambda user: user.is_staff
SILKY_MAX_RESPONSE_BODY_SIZE = 1024


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    }
}

Q_CLUSTER = {
    "name": "DJRedis",
    "workers": 8,
    "recycle": 20,
    "timeout": 30,
    "retry": 35,
    "orm": "default",
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", default="http://localhost/static/")
STATIC_ROOT = os.environ.get("STATIC_ROOT", default="/opt/django-static")

MEDIA_URL = os.environ.get("MEDIA_URL", default="http://localhost/media/")
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", default="/opt/django-media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Docs

SPECTACULAR_SETTINGS = {
    "SCHEMA_PATH_PREFIX_INSERT": os.environ.get("SCRIPT_NAME", default="/api")
}
